### ISSUE TITLE
Controller should not just publish their data

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.authentication#41] opened 2017-07-19 08:51 UTC
I am not sure if there already exists such an issue so I create this one to reference it from within others.

As long as controller just publish their data when it changes, read rights are useless because everyone who is willing to listen will get the current state.

One possible solution to this would be that controller just notify that their data has changed and remotes will then start a request with their specific rights. A disadvantage of this is that it produces a lot of overhead  communication for a simple data update.

**Comment by Harmageddon** [comment] 2017-08-02 11:22
Duplicate of #10

**Closed as completed by Harmageddon** 2017-08-02 11:22 UTC
Labels: enhancement
